export interface Testimony {
  id: string;
  title: string;
  description: string;
  authorName?: string;
  thumbnail?: string;
  videoUrl: string;
  /** seconds */
  duration?: number;
  category?: string;
  keywords: string[];
  createdAt: string | null;
  publishedAt: string | null;
  isPublished: boolean;
  isFeatured: boolean;
  isDownloadable: boolean;
}

export type LiveSourceType = 'hls' | 'youtube' | 'unknown';

export interface LiveConfig {
  isLive: boolean;
  streamUrl?: string;
  sourceType?: LiveSourceType;
  /** Regenerated by the admin each time they go live; live chat is scoped to this. */
  sessionId?: string;
  title?: string;
  thumbnail?: string;
  description?: string;
}

export type NotificationType = 'testimony' | 'resource' | 'live' | 'announcement' | 'featured';

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  type: NotificationType;
  contentId?: string;
  createdAt: string | null;
  published: boolean;
}

export interface NotificationPrefs {
  testimonies: boolean;
  live: boolean;
  announcements: boolean;
}

export interface Page<T> {
  items: T[];
  cursor?: unknown;
  hasMore: boolean;
}

export type DownloadKind = 'testimony';
export type DownloadStatus = 'downloading' | 'done' | 'failed';
export type DownloadFailure = 'network' | 'storage' | 'http' | 'unsupported' | 'unknown';

export interface DownloadItem {
  key: string; // `${kind}:${id}`
  id: string;
  kind: DownloadKind;
  title: string;
  thumbnail?: string;
  remoteUrl: string;
  fileName: string; // relative to the downloads directory (absolute paths change between app updates on iOS)
  fileType: string;
  status: DownloadStatus;
  progress: number; // 0..1
  sizeBytes?: number;
  failure?: DownloadFailure;
  createdAt: number;
  data: Testimony; // snapshot so details work offline
}

export type SponsorshipStatus = 'pending' | 'approved' | 'rejected';

export interface Sponsorship {
  id: string;
  uid: string;
  userEmail: string | null;
  amount?: string;
  note?: string;
  receiptUrl: string;
  status: SponsorshipStatus;
  createdAt: string | null;
}
